# Generated by Django 4.0.5 on 2022-06-21 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('joined_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
